# Generated by Django 3.2.5 on 2021-07-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnew',
            fields=[
                ('personid', models.AutoField(db_column='PersonID', primary_key=True, serialize=False)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('hiredate', models.DateTimeField(blank=True, db_column='HireDate', null=True)),
                ('enrollmentdate', models.DateTimeField(blank=True, db_column='EnrollmentDate', null=True)),
                ('discriminator', models.CharField(db_column='Discriminator', max_length=50)),
            ],
            options={
                'db_table': 'Personnew',
            },
        ),
    ]
